### ISSUE TITLE
Remove every reference to google servers.

### ISSUE THREAD

**Issue by opi** [zamentur/strut_ynh#9]
See https://github.com/zamentur/strut_ynh/blob/master/sources%2Fpreview_export%2Freveal.html#L126

**Comment by zamentur** [comment]
Thanks for your alert. I believed I have removed it everywhere.

**Comment by zamentur** [comment]
I have removed google-analytics and google fonts. I grep twitter, yahoo, facebook and piwik too.
Let me know if you find other trackers.
Thanks

**Comment by opi** [comment]
Seems ok to me. Thanks a lot
